import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FullscreenProvider } from "./FullscreenContext";
import { AppProvider } from '@/contexts/AppContext';
import {LayoutClient}  from './LayoutClient';
import { headers } from 'next/headers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"], 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Server-side device detection
  const headersList = await headers();
  const ua = headersList.get('user-agent') || null;
  const isMobile = /android|iphone|ipad|ipod|mobile|tablet/i.test(ua || '');

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FullscreenProvider><AppProvider>
          <LayoutClient isMobile={isMobile}>
            {children}
          </LayoutClient>
        </AppProvider></FullscreenProvider>
      </body>
    </html>
  );
}
